## 금융 뉴스 키워드(빈도) 분석
- 빅카인즈 자료 참고

### 함수 실행

In [24]:
!pip install konlpy

Requirement already satisfied: konlpy in /usr/local/lib/python3.10/dist-packages (0.6.0)
Requirement already satisfied: JPype1>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.4.1)
Requirement already satisfied: lxml>=4.1.0 in /usr/local/lib/python3.10/dist-packages (from konlpy) (4.9.3)
Requirement already satisfied: numpy>=1.6 in /usr/local/lib/python3.10/dist-packages (from konlpy) (1.22.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from JPype1>=0.7.0->konlpy) (23.1)

In [25]:
import pandas as pd
from konlpy.tag import Okt
okt = Okt()

In [26]:
reviews_df = pd.read_csv('/content/drive/MyDrive/DataYC_project/키워드 선정/NewsResult_20230430-20230730.csv',encoding='cp949')

In [ ]:
reviews_df.head(5)

In [28]:
len(reviews_df)

20000

### 명사 추출

In [29]:
def tokenizer(text):
    morph = okt.pos(text)
    words = []
    for word, tag in morph:
        if tag in ['Noun']:
            if len(word) > 1:
                words.append(word)
    return words

In [30]:
reviews_df= reviews_df.astype('str')

In [31]:
reviews_df['제목'] = reviews_df['제목'].apply(tokenizer)

In [32]:
reviews_df['제목']

0                       [충주시, 무더위, 극복, 먹거리, 나눔]
1                          [개인, 포홀, 기관, 평가, 실적]
2                    [교육부, 이주호, 교권, 보호, 조례, 폐지]
3                        [장기, 수익률, 투자자, 인내, 시간]
4            [서병수, 자식, 사랑, 학교, 난장판, 교사, 권위, 존중]
                          ...
19995          [울산, 정보산업, 진흥, 해운, 디지털, 서비스, 추진]
19996      [천단, 축협, 우박, 피해, 축산, 농가, 재해, 원금, 전달]
19997                 [부산, 위증, 법질서, 방해, 사범, 엄단]
19998            [부대, 호러, 체험, 울산, 축제, 프로그램, 논란]
19999    [희극, 하트, 돌고래, 비극, 기후, 위기, 경고, 앵커, 리포트]
Name: 제목, Length: 20000, dtype: object

In [33]:
reviews_df.to_csv('명사추출.csv', encoding='utf-8')

In [34]:
reviews_df= reviews_df.astype('str')

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, ngram_range=(1, 1))
tdm = cv.fit_transform(reviews_df.제목)
word_count_tf = pd.DataFrame({'단어': cv.get_feature_names_out(), '빈도': tdm.sum(axis=0).flat})

word_count_tf

         단어  빈도
0        가게  10
1        가격  66
2        가계   6
3        가공  15
4        가구  89
...     ...  ..
4995     히잡   7
4996     히트   5
4997    히틀러   6
4998     힐링  14
4999  힐스테이트  11

[5000 rows x 2 columns]

In [36]:
word_count_tf = word_count_tf.sort_values('빈도', ascending=False)
word_count_tf

       단어   빈도
3889   지원  513
4684   한국  408
443    교사  394
4561   포토  393
1930   사업  379
...   ...  ...
739    나인    4
817   노숙인    4
3465  장원영    4
1766  부시장    4
3126   윤정    4

[5000 rows x 2 columns]

## 결과값

In [37]:
word_count_tf = word_count_tf.reset_index(drop=True)
word_count_tf.index = word_count_tf.index + 1

word_count_tf

       단어   빈도
1      지원  513
2      한국  408
3      교사  394
4      포토  393
5      사업  379
...   ...  ...
4996   나인    4
4997  노숙인    4
4998  장원영    4
4999  부시장    4
5000   윤정    4

[5000 rows x 2 columns]

In [38]:
## 인덱스 123 순서 + 빈도 오름차순 정렬 csv 파일 출력

word_count_tf.to_csv('빈도.csv', encoding='cp949')